export const NAV_ACTIVATE = 'NAV_ACTIVATE';

export const USER_ROLE = {
  ROLE_ADMIN: "ADMIN",
  ROLE_USER: "USER"
};

export const USER_TYPE = {
  MERCHANDISING: "MERCHANDISING",
  SAMPLING: "SAMPLING",
  FACTORY: "FACTORY"
};

export const USER_LEVEL = {
  LEVEL0: "LEVEL0",
  LEVEL1: "LEVEL1",
  LEVEL2: "LEVEL2",
  LEVEL3: "LEVEL3",
  LEVEL4: "LEVEL4"
};

export const MISC_CONSTANTS = {
  INITIALIZE_TEAM: 'INITIALIZE_TEAM',
  INITIALIZE_PROBLEM: 'INITIALIZE_PROBLEM',
  INITIALIZE_BUYER: 'INITIALIZE_BUYER',
  INITIALIZE_SECTION: 'INITIALIZE_SECTION',
  INITIALIZE_DEPARTMENT: 'INITIALIZE_DEPARTMENT',
  INITIALIZE_PROBLM: 'INITIALIZE_PROBLM',
  INITIALIZE_DESGN: 'INITIALIZE_DESGN',
  STORE_INITIALIZED: 'STORE_INITIALIZED'
};

export const USER_CONSTANTS = {
  INITIALIZE_USER: 'INITIALIZE_USER',
  USER_AUTH_PROGRESS: 'USER_AUTH_PROGRESS',
  USER_AUTH_SUCCESS: 'USER_AUTH_SUCCESS',
  USER_AUTH_FAIL: 'USER_AUTH_FAIL',
  USER_BAD_REQUEST: 'USER_BAD_REQUEST',
  USER_ADD_FORM_TOGGLE: 'USER_ADD_FORM_TOGGLE',
  USER_ADD_SUCCESS: 'USER_ADD_SUCCESS',
  USER_ADD_FAIL: 'USER_ADD_FAIL',
  USER_EDIT_FORM_TOGGLE: 'USER_EDIT_FORM_TOGGLE',
  USER_EDIT_SUCCESS: 'USER_EDIT_SUCCESS',
  USER_EDIT_FAIL: 'USER_EDIT_FAIL',
  USER_REMOVE_PROGRESS: 'USER_REMOVE_PROGRESS',
  USER_REMOVE_SUCCESS: 'USER_REMOVE_SUCCESS',
  USER_REMOVE_FAIL: 'USER_REMOVE_FAIL',
  USER_FILTER: 'USER_FILTER',
  USER_SORT: 'USER_SORT',
  USER_CHANGE_PASSWD: 'USER_CHANGE_PASSWD',
  USER_BUSY: 'USER_BUSY',
  USER_SEARCH_SUCCESS: 'USER_SEARCH_SUCCESS',
  USER_SEARCH_FAIL: 'USER_SEARCH_FAIL'
};

export const ISSUE_CONSTANTS = {
  ISSUE_SYNC_PROGRESS: 'ISSUE_SYNC_PROGRESS',
  ISSUE_SYNC_SUCCESS: 'ISSUE_SYNC_SUCCESS',
  ISSUE_SYNC_FAIL: 'ISSUE_SYNC_FAIL',
  ISSUE_ADD_FORM_TOGGLE: 'ISSUE_ADD_FORM_TOGGLE',
  ISSUE_VIEW_TOGGLE: 'ISSUE_VIEW_TOGGLE',
  ISSUE_ADD_SUCCESS: 'ISSUE_ADD_SUCCESS',
  ISSUE_ADD_FAIL: 'ISSUE_ADD_FAIL',
  ISSUE_EDIT_FORM_TOGGLE: 'ISSUE_EDIT_FORM_TOGGLE',
  ISSUE_EDIT_SUCCESS: 'ISSUE_EDIT_SUCCESS',
  ISSUE_EDIT_FAIL: 'ISSUE_EDIT_FAIL',
  ISSUE_REMOVE_PROGRESS: 'ISSUE_REMOVE_PROGRESS',
  ISSUE_REMOVE_SUCCESS: 'ISSUE_REMOVE_SUCCESS',
  ISSUE_REMOVE_FAIL: 'ISSUE_REMOVE_FAIL',
  ISSUE_FILTER: 'ISSUE_FILTER',
  ISSUE_SORT: 'ISSUE_SORT',
  ISSUE_BAD_REQUEST: 'ISSUE_BAD_REQUEST',
  ISSUE_BUSY: 'ISSUE_BUSY'
};
