INSERT INTO buyer (`buyer_id`,`name`,`team`) VALUES
(1,'Landmark','TL-Rajeshwari'),
(2,'UCB','TL-Rajeshwari'),
(3,'Strong Sui','TL-Rajeshwari'),
(4,'Edifice','TL-Rajeshwari'),
(5,'Other','TL-Rajeshwari'),
(6,'TML - Formal','TL-Amit'),
(7,'TML - Casual & Women','TL-Amit'),
(8,'Carrefour','TL-Amit'),
(9,'PRL','TL-Amit'),
(10,'Moss Bros','TL-Amit'),
(11,'Other','TL-Amit'),
(12,'Dressmann','TL-Tanushree'),
(13,'Reiss','TL-Tanushree'),
(14,'Jaeger','TL-Tanushree'),
(15,'Esprit','TL-Tanushree'),
(16,'BS- Selected','TL-Tanushree'),
(17,'BS- Jack & Jones','TL-Tanushree'),
(18,'BS- Jack & Jones India','TL-Tanushree'),
(19,'Tommy Hilfiger','TL-Tanushree'),
(20,'Other','TL-Tanushree'),
(21,'Thomas Pink','TL-Malini'),
(22,'Celio','TL-Malini'),
(23,'Defursac','TL-Malini'),
(24,'CT','TL-Malini'),
(25,'Hackett','TL-Malini'),
(26,'Mango','TL-Malini'),
(27,'Peter Jackson','TL-Malini'),
(28,'H&C','TL-Malini'),
(29,'Other','TL-Malini');

